#!/bin/sh

GREEN='\033[42m'


while true; do
    read -p "Would you like to install or update this instance? (i/U) " answer
    case $answer in
        [Ii]* ) make init; make update; break;;
        [uU]* ) make update;;
        * ) make update; echo -e '\033[32mExiting installer\033[m';exit;;
    esac
done