hyprctl keyword windowrule "workspace unset,kitty"
hyprctl keyword windowrule "workspace unset,brave"
hyprctl keyword windowrule "workspace unset,prismlauncher"
hyprctl keyword windowrule "workspace unset,kitty"
hyprctl keyword windowrule "workspace unset,discord"